/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PDFData = IDL.Record({
  'contentType' : IDL.Text,
  'filename' : IDL.Text,
  'bytes' : IDL.Vec(IDL.Nat8),
});
export const ApplicationStatus = IDL.Record({
  'status' : IDL.Text,
  'applicantName' : IDL.Text,
  'applicationId' : IDL.Text,
  'lastUpdated' : Time,
  'visaType' : IDL.Text,
  'comments' : IDL.Opt(IDL.Text),
  'applicantEmail' : IDL.Text,
  'attachment' : IDL.Opt(PDFData),
});
export const VisaRecord = IDL.Record({
  'id' : IDL.Text,
  'visaLabel' : IDL.Text,
  'expiryDate' : Time,
  'createdAt' : Time,
  'updatedAt' : Time,
  'conditions' : IDL.Opt(IDL.Text),
  'reminders' : IDL.Vec(Time),
  'grantReference' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateApplicationStatus' : IDL.Func([ApplicationStatus], [], []),
  'createVisaRecord' : IDL.Func([VisaRecord], [], []),
  'deleteApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteVisaRecord' : IDL.Func([IDL.Text], [], []),
  'getAllApplicationStatuses' : IDL.Func(
      [],
      [IDL.Vec(ApplicationStatus)],
      ['query'],
    ),
  'getApplicationStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ApplicationStatus)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPDF' : IDL.Func([IDL.Nat], [IDL.Opt(PDFData)], ['query']),
  'getUpcomingReminders' : IDL.Func([], [IDL.Vec(VisaRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisaRecords' : IDL.Func([], [IDL.Vec(VisaRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storePDF' : IDL.Func([PDFData], [IDL.Nat], []),
  'updateVisaRecord' : IDL.Func([IDL.Text, VisaRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PDFData = IDL.Record({
    'contentType' : IDL.Text,
    'filename' : IDL.Text,
    'bytes' : IDL.Vec(IDL.Nat8),
  });
  const ApplicationStatus = IDL.Record({
    'status' : IDL.Text,
    'applicantName' : IDL.Text,
    'applicationId' : IDL.Text,
    'lastUpdated' : Time,
    'visaType' : IDL.Text,
    'comments' : IDL.Opt(IDL.Text),
    'applicantEmail' : IDL.Text,
    'attachment' : IDL.Opt(PDFData),
  });
  const VisaRecord = IDL.Record({
    'id' : IDL.Text,
    'visaLabel' : IDL.Text,
    'expiryDate' : Time,
    'createdAt' : Time,
    'updatedAt' : Time,
    'conditions' : IDL.Opt(IDL.Text),
    'reminders' : IDL.Vec(Time),
    'grantReference' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateApplicationStatus' : IDL.Func([ApplicationStatus], [], []),
    'createVisaRecord' : IDL.Func([VisaRecord], [], []),
    'deleteApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteVisaRecord' : IDL.Func([IDL.Text], [], []),
    'getAllApplicationStatuses' : IDL.Func(
        [],
        [IDL.Vec(ApplicationStatus)],
        ['query'],
      ),
    'getApplicationStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ApplicationStatus)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPDF' : IDL.Func([IDL.Nat], [IDL.Opt(PDFData)], ['query']),
    'getUpcomingReminders' : IDL.Func([], [IDL.Vec(VisaRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisaRecords' : IDL.Func([], [IDL.Vec(VisaRecord)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storePDF' : IDL.Func([PDFData], [IDL.Nat], []),
    'updateVisaRecord' : IDL.Func([IDL.Text, VisaRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };