/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApplicationStatus {
  'status' : string,
  'applicantName' : string,
  'applicationId' : string,
  'lastUpdated' : Time,
  'visaType' : string,
  'comments' : [] | [string],
  'applicantEmail' : string,
  'attachment' : [] | [PDFData],
}
export interface PDFData {
  'contentType' : string,
  'filename' : string,
  'bytes' : Uint8Array,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisaRecord {
  'id' : string,
  'visaLabel' : string,
  'expiryDate' : Time,
  'createdAt' : Time,
  'updatedAt' : Time,
  'conditions' : [] | [string],
  'reminders' : Array<Time>,
  'grantReference' : [] | [string],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateApplicationStatus' : ActorMethod<
    [ApplicationStatus],
    undefined
  >,
  'createVisaRecord' : ActorMethod<[VisaRecord], undefined>,
  'deleteApplicationStatus' : ActorMethod<[string, string], undefined>,
  'deleteVisaRecord' : ActorMethod<[string], undefined>,
  'getAllApplicationStatuses' : ActorMethod<[], Array<ApplicationStatus>>,
  'getApplicationStatus' : ActorMethod<
    [string, string],
    [] | [ApplicationStatus]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserProfileByPrincipal' : ActorMethod<
    [Principal],
    [] | [UserProfile]
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUpcomingReminders' : ActorMethod<[], Array<VisaRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisaRecords' : ActorMethod<[], Array<VisaRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateVisaRecord' : ActorMethod<[string, VisaRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];